title: Arav Parikh # your name (or website title) here
logo: "/images/IMG_0472.jpg?raw=true" # your photo (or logo) here
description: > #
  I'm a freshman at Vista Del Lago with a passion for AI and machine learning, especially in healthcare applications. I love exploring how technology can solve real-world problems, such as using AI to improve diagnosis and treatment pathways.
  <br><br>
  Currently, I'm working on projects focused on chronic pain prediction and risk factor analysis. As part of my school's CS club, I enjoy taking on coding challenges and continuously expanding my knowledge in technology and science.
  <br><br>
  <a href="https://www.linkedin.com/in/arav-parikh-1853b92b6/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here (replace with actual ID)

