title: Arav Parikh # your name (or website title) here
logo: "raw=true" # your photo (or logo) here
description: > #
  I'm a freshman at Vista Del Lago with a passion for AI and machine learning, especially in healthcare applications. 
  <br><br>
  Currently, I'm working on projects focused on chronic pain prediction and risk factor analysis.
  <br><br>
  Methods to Contact Me:
  <br><br>
  <a href="https://www.linkedin.com/in/arav-parikh-1853b92b6/">View My LinkedIn Profile</a> 
  <br><br>
  <span style="cursor:pointer; color:blue; text-decoration:underline;" onclick="showInfo('discord')">Discord Username</span> 
  <br><br>
  <span style="cursor:pointer; color:blue; text-decoration:underline;" onclick="showInfo('email')">My Email Address</span>

<div id="infoModal" style="display:none; position:fixed; top:50%; left:50%; transform:translate(-50%, -50%); background:white; border:1px solid #ccc; padding:20px; z-index:1000;">
  <span id="infoText"></span>
  <br><br>
  <button onclick="closeModal()" style="cursor:pointer;">Close</button>
</div>

<script>
  function showInfo(type) {
    let infoText = '';
    if (type === 'discord') {
      infoText = 'Your Discord Username: acp111';
    } else if (type === 'email') {
      infoText = 'Your Email Address: aravparikh712@gmail.com';
    }
    document.getElementById('infoText').innerText = infoText;
    document.getElementById('infoModal').style.display = 'block';
  }

  function closeModal() {
    document.getElementById('infoModal').style.display = 'none';
  }
</script>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here (replace with actual ID)


