title: Arav Parikh # Your name (or website title) here
remote_theme: cotes2020/jekyll-theme-chirpy # Change to a dark theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Optional config
theme: chirpy # Ensure the theme supports dark mode
description: > #
  I'm a freshman at Vista Del Lago with a passion for AI and machine learning, especially in healthcare applications. 
  <br><br>
  Currently, I'm working on projects focused on chronic pain prediction and risk factor analysis.
  <br><br>
  Methods to Contact Me:
  <br><br>
  <a href="https://www.linkedin.com/in/arav-parikh-1853b92b6/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/aravparikh/">View My Github Profile</a>
  <br><br>
  <span style="cursor:pointer; color: grey; text-decoration: underline;" onclick="showInfo('email')">My Email Address: aravparikh.1@gmail.com</span>

# Enable dark mode settings (theme-specific)
dark_mode: true
